export { handler as authorization } from './lib/authorization';
export { handler as consent } from './lib/consent';
export { handler as jwks } from './lib/jwks';
export { handler as login } from './lib/login';
export { handler as openidConfiguration } from './lib/openid-configuration';
export { handler as token } from './lib/token';
export { handler as introspection } from './lib/token/introspection';
export { handler as revocation } from './lib/token/revocation';
export { handler as userinfo } from './lib/userinfo';
