export enum ERROR_CODE {
  ACCESS_DENIED = 'access_denied',
  ACCOUNT_SELECTION_REQUIRED = 'account_selection_required',
  CONSENT_REQUIRED = 'consent_required',
  INTERACTION_REQUIRED = 'interaction_required',
  INVALID_CLIENT = 'invalid_client',
  INVALID_GRANT = 'invalid_grant',
  INVALID_REQUEST = 'invalid_request',
  INVALID_REQUEST_OBJECT = 'invalid_request_object',
  INVALID_REQUEST_URI = 'invalid_request_uri',
  INVALID_SCOPE = 'invalid_scope',
  INVALID_TOKEN = 'invalid_token',
  LOGIN_REQUIRED = 'login_required',
  REGISTRATION_NOT_SUPPORTED = 'registration_not_supported',
  REQUEST_NOT_SUPPORTED = 'request_not_supported',
  REQUEST_URI_NOT_SUPPORTED = 'request_uri_not_supported',
  SERVER_ERROR = 'server_error',
  TEMPORARILY_UNAVAILABLE = 'temporarily_unavailable',
  UNAUTHORIZED_CLIENT = 'unauthorized_client',
  UNSUPPORTED_GRANT_TYPE = 'unsupported_grant_type',
  UNSUPPORTED_RESPONSE_TYPE = 'unsupported_response_type',
  UNSUPPORTED_TOKEN_TYPE = 'unsupported_token_type',
}
