export enum RESPONSE_TYPE {
  CODE = 'code',
  ID_TOKEN = 'id_token',
  TOKEN = 'token',
}

export enum AUTHENTICATION_FLOW {
  AUTHORIZATION_CODE = 'Authorization Code Flow',
  IMPLICIT = 'Implicit Flow',
  HYBRID = 'Hybrid Flow',
}

export const RESPONSE_TYPE_FLOW = {
  [AUTHENTICATION_FLOW.AUTHORIZATION_CODE]: [[RESPONSE_TYPE.CODE]],
  [AUTHENTICATION_FLOW.IMPLICIT]: [
    [RESPONSE_TYPE.ID_TOKEN],
    [RESPONSE_TYPE.ID_TOKEN, RESPONSE_TYPE.TOKEN],
  ],
  [AUTHENTICATION_FLOW.HYBRID]: [
    [RESPONSE_TYPE.CODE, RESPONSE_TYPE.ID_TOKEN],
    [RESPONSE_TYPE.CODE, RESPONSE_TYPE.TOKEN],
    [RESPONSE_TYPE.CODE, RESPONSE_TYPE.ID_TOKEN, RESPONSE_TYPE.TOKEN],
  ],
};
