import { CLAIM } from './claim';

export enum SCOPE {
  OPENID = 'openid',
  PROFILE = 'profile',
  EMAIL = 'email',
  ADDRESS = 'address',
  PHONE = 'phone',
}

export const SCOPE_CLAIMS = {
  [SCOPE.OPENID]: [
    CLAIM.SUB,
    CLAIM.ISS,
    CLAIM.AUD,
    CLAIM.EXP,
    CLAIM.IAT,
    CLAIM.AUTH_TIME,
  ],
  [SCOPE.PROFILE]: [
    CLAIM.NAME,
    CLAIM.FAMILY_NAME,
    CLAIM.GIVEN_NAME,
    CLAIM.MIDDLE_NAME,
    CLAIM.NICKNAME,
    CLAIM.PREFERRED_USERNAME,
    CLAIM.PICTURE,
    CLAIM.UPDATED_AT,
  ],
  [SCOPE.EMAIL]: [CLAIM.EMAIL, CLAIM.EMAIL_VERIFIED],
  [SCOPE.ADDRESS]: [CLAIM.ADDRESS],
  [SCOPE.PHONE]: [CLAIM.PHONE_NUMBER, CLAIM.PHONE_NUMBER_VERIFIED],
};
