name: Test, build & deploy to NPM

on:
  push:
    branches:
      - 'main'
      - 'next'

jobs:
  setup:
    name: Test, build & deploy to NPM
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node_version: 14
          registry-url: 'https://registry.npmjs.org'
          scope: '@saschazar'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: |
            npm-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            npm-deps-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build packages
        run: yarn build

      - name: Deploy pre-release
        if: ${{ github.ref == 'refs/heads/next' }}
        run: yarn publish:prerelease

      - name: Deploy release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: yarn publish:release
